name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./dist
    
    - name: Switch to Release Folder
      run: |
        cd dist
        ls -la
    
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag

    - name: Test
      run: |
        echo ${{ steps.get-latest-tag.outputs.tag }}

    - name: Release on Github
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NAME: "gh-actions-practice ${{ steps.get-latest-tag.outputs.tag }}"
      with:
        args: |
          dist/gh-actions-practice-${{ steps.get-latest-tag.outputs.tag }}.zip