name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag

    - name: Test
      run: |
        echo ${{ steps.get-latest-tag.outputs.tag }}

    - name: Release on Github
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF: "refs/tags/${{ steps.get-latest-tag.outputs.tag }}"
        RELEASE_NAME: "gh-actions-practice ${{ steps.get-latest-tag.outputs.tag }}"
      with:
        args: |
          release/gh-actions-practice-${{ steps.get-latest-tag.outputs.tag }}.zip


# name: Release
# on:
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#     - name: Checkout repository
#       uses: actions/checkout@v3
#       with:
#         ref: ${{ github.sha }}
#         fetch-depth: '0'

#     - name: Create Release Folder
#       run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    
#     - name: Switch to Release Folder
#       run: |
#         cd release
#         ls -la
    
#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         WITH_V: true

#     - name: Get tag
#       id: get_tag
#       run: |
#         echo "name=TAG::${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
#         echo "name=VERSION::${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    
