name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get the tag
      id: get_tag
      run: |
        echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: roaldarbol
    
    - name: Release on Github
      uses: docker://antonyurchenko/git-release:v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "false"
        ALLOW_TAG_PREFIX: "true"
        RELEASE_NAME: "LaPreprint ${{ steps.get_tag.outputs.version }}"
      with:
        args: |
          dist/lapreprint-${{ steps.get_tag.outputs.version }}.zip